# Generated by Django 5.2.8 on 2025-12-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='name')),
                ('email', models.CharField(verbose_name='email')),
                ('message', models.CharField(verbose_name='message')),
            ],
        ),
    ]
